# KnpPaginatorBunle:
knp_paginator:
    page_range: 5  
    default_options:  
        page_name: page  
        sort_field_name: sort  
        sort_direction_name: direction
        distinct: true  
    template:   
        pagination: custom_pagination.html.twig
        sortable: KnpPaginatorBundle/Pagination:sortable_link.html.twig


 #config/packages/paginator.yaml
