BackendBundle\Entity\User:
    properties:
        name: 
          - NotBlank: {message: "El nombre no puede estar vacio"}

        surname: 
          - NotBlank: {message: "El apellido no puede estar vacio"}
        
        nick: 
          - NotBlank: {message: "El nick no puede estar vacio"}

        email:
          - NotBlank: {message: "El email no puede estar vacio"} 
          - Email: 
               message: El email {{ value }} no es valido.
               checkMX: false