BackendBundle\Entity\Notification:
    type: entity
    table: notifications
    indexes:
        fk_notifications_users:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        typeId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: type_id
        readed:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        extra:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
